name: CI with Docker

on:
  push:
  pull_request:
    branches:
      - main 

jobs:
  run-tests:
    name: Run Tests in Docker
    runs-on: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Run tests in Docker
        run: |
          docker run devops1
